### ISSUE TITLE
test run not working

### ISSUE THREAD

**Issue by splaisan** [vmikk/NextITS#2]
Hi Vladimir,

On the doc page (https://next-its.github.io/installation/) there is a _test_ command that I do not succeed to run.

```
nextflow run vmikk/nextits -r main -profile test
N E X T F L O W  ~  version 22.10.1
Unknown configuration profile: 'test'
```

I tried replacing main by 0.5.0 without more success

```
$ nextflow run vmikk/nextits -r 0.5.0 -profile test
N E X T F L O W  ~  version 22.10.1
Unknown configuration profile: 'test'
```

<details>
  <summary>log</summary>

```
Aug-29 12:14:28.633 [main] DEBUG nextflow.cli.Launcher - $> nextflow run vmikk/nextits -r 0.5.0 -profile test
Aug-29 12:14:28.693 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.10.1
Aug-29 12:14:28.717 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/luna.kuleuven.be/u0002316/.nextflow/plugins; core-plugins: nf-amazon@1.11.0,nf-azure@0.14.2,nf-codecommit@0.1.2,nf-console@1.0.4,nf-ga4gh@1.0.4,nf-google@1.4.4,nf-tower@1.5.5,nf-wave@0.5.2
Aug-29 12:14:28.727 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Aug-29 12:14:28.728 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Aug-29 12:14:28.731 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Aug-29 12:14:28.741 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Aug-29 12:14:28.756 [main] DEBUG nextflow.scm.ProviderConfig - Using SCM config path: /home/luna.kuleuven.be/u0002316/.nextflow/scm
Aug-29 12:14:29.692 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/luna.kuleuven.be/u0002316/.nextflow/assets/vmikk/nextits/.git/config; branch: master; remote: origin; url: https://github.com/vmikk/NextITS.git
Aug-29 12:14:29.714 [main] DEBUG nextflow.scm.RepositoryFactory - Found Git repository result: [RepositoryFactory]
Aug-29 12:14:29.722 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/luna.kuleuven.be/u0002316/.nextflow/assets/vmikk/nextits/.git/config; branch: master; remote: origin; url: https://github.com/vmikk/NextITS.git
Aug-29 12:14:30.533 [main] DEBUG nextflow.config.ConfigBuilder - Found config base: /home/luna.kuleuven.be/u0002316/.nextflow/assets/vmikk/nextits/nextflow.config
Aug-29 12:14:30.534 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /home/luna.kuleuven.be/u0002316/.nextflow/assets/vmikk/nextits/nextflow.config
Aug-29 12:14:30.542 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `test`
Aug-29 12:14:30.737 [main] DEBUG nextflow.config.ConfigBuilder - Available config profiles: [singularity, hpc, docker]
Aug-29 12:14:30.754 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Unknown configuration profile: 'test'
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
	at nextflow.config.ConfigBuilder.checkValidProfile(ConfigBuilder.groovy:511)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.config.ConfigBuilder.buildConfig0(ConfigBuilder.groovy:385)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at nextflow.config.ConfigBuilder.buildGivenFiles(ConfigBuilder.groovy:317)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.config.ConfigBuilder.buildConfigObject(ConfigBuilder.groovy:780)
	at nextflow.config.ConfigBuilder.build(ConfigBuilder.groovy:793)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:307)
	at nextflow.cli.Launcher.run(Launcher.groovy:487)
	at nextflow.cli.Launcher.main(Launcher.groovy:646)
```

</details>

I cloned the git and have the test_data folder local, should I do something extra to run the test?

but the image seems to be ready to do something

```
$ nextflow run vmikk/nextits -r 0.5.0 --help
N E X T F L O W  ~  version 22.10.1
Launching `https://github.com/vmikk/nextits` [suspicious_banach] DSL2 - revision: 6f9e110b9d [0.5.0]
Please provide the input file with sequences in FASTQ.gz format with `--input` parameter.
```

S

**Comment by vmikk** [comment]
Unfortunately, test run is not implemented yet.
